---
title: "Lab 2"
author: "Axel Holmberg (axeho681)"
date: "9/22/2020"
output: pdf_document
---

```{r Set up, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Task 1

```{r task_1, echo=FALSE}
library(HMM)

##### TASK 1 #####

# 10 Different places
states <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
symbol_states <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

# Equal probability of it moving and staying
transition_probs <- matrix(
                   c(0.5, 0.5, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0.5, 0.5, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0.5, 0.5, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0.5, 0.5, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0.5, 0.5, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0.5, 0.5, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0.5, 0.5, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0.5, 0.5, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0.5, 0.5,
                     0.5, 0, 0, 0, 0, 0, 0, 0, 0, 0.5), 
                     nrow=10, ncol=10)


# Equal probability of it being i-2,i-1,i,i+1 and i+2
emission_probs <-  matrix(
                    c(0.2, 0.2, 0.2, 0, 0, 0, 0, 0, 0.2, 0.2,
                      0.2, 0.2, 0.2, 0.2, 0, 0, 0, 0, 0, 0.2,
                      0.2, 0.2, 0.2, 0.2, 0.2, 0, 0, 0, 0, 0,
                      0, 0.2, 0.2, 0.2, 0.2, 0.2, 0, 0, 0, 0,
                      0, 0, 0.2, 0.2, 0.2, 0.2, 0.2, 0, 0, 0,
                      0, 0, 0, 0.2, 0.2, 0.2, 0.2, 0.2, 0, 0,
                      0, 0, 0, 0, 0.2, 0.2, 0.2, 0.2, 0.2, 0,
                      0, 0, 0, 0, 0, 0.2, 0.2, 0.2, 0.2, 0.2,
                      0.2, 0, 0, 0, 0, 0, 0.2, 0.2, 0.2, 0.2,
                      0.2, 0.2, 0, 0, 0, 0, 0, 0.2, 0.2, 0.2), 
                      nrow=10, ncol=10)


hmm <-
  initHMM(States = states,
          Symbols = symbol_states,
          startProbs = rep(0.1, 10),
          transProbs = transition_probs,
          emissionProbs = emission_probs
          )
print("States:")
states
print("Symbol states:")
symbol_states
print("Transition matrix:")
transition_probs
print("Emission matrix:")
emission_probs
print("Summary of HMM:")
summary(hmm)
```

## Task 2

```{r task_2, echo=FALSE}
set.seed(12345)
simulated_steps <- simHMM(hmm,100)
print("The observed simulated steps are:")
simulated_steps$observation
```

## Task 3

```{r task_3, echo=FALSE}

##### TASK 3 #####

filter_function <- function(alphas) {
  filtered <- matrix(NA,
                     nrow = dim(alphas)[1],
                     ncol = dim(alphas)[2])
  for (t in 1:dim(alphas)[1]) {
    filtered[t,] <- alphas[t,] / sum(alphas[t,])
  }
  
  return(filtered)
}


smooth_function <- function(alphas, betas) {
  smoothed <- matrix(NA,
                     nrow = dim(alphas)[1],
                     ncol = dim(alphas)[2])
  
  for (t in 1:dim(alphas)[1]) {
    smoothed[t, ] <-
      (alphas[t, ] * betas[t, ]) / (sum(alphas[t, ] * betas[t, ]))
  }
  
  return (smoothed)
}


hmm_forward_alpha <-
  exp(forward(
    hmm = hmm,
    observation = simulated_steps$observation
  ))

hmm_backward_beta <-
 exp( backward(
    hmm = hmm,
    observation = simulated_steps$observation
  ))

filtered <- filter_function(hmm_forward_alpha)

smoothed <-
  smooth_function(hmm_forward_alpha, hmm_backward_beta)

viterbi <- viterbi(hmm, simulated_steps$observation)

```

The most probable path is:

```{r task_3_2, echo=FALSE}
viterbi
```


## Task 4

```{r task_4_1, echo=FALSE}
accuracy_function <- function(prediction, true) {
  confusion_matrix <- table(prediction, true)
  accuracy <- sum(diag(confusion_matrix))/sum(confusion_matrix)
  return (accuracy)
}

filtered_prediction <- apply(t(filtered), MARGIN = 1, which.max)
smoothed_prediction <- apply(t(smoothed), MARGIN = 1, which.max)


accuracy_function(filtered_prediction, simulated_steps$states)
accuracy_function(smoothed_prediction, simulated_steps$states)
accuracy_function(viterbi, simulated_steps$states)


##### TASK 5 #####
#Different seed
set.seed(67890)
simulated_steps_seeded <- simHMM(hmm,100)

hmm_forward_alpha_seeded <-
  exp(forward(
    hmm = hmm,
    observation = simulated_steps_seeded$observation
  ))

hmm_backward_beta_seeded <-
  exp( backward(
    hmm = hmm,
    observation = simulated_steps_seeded$observation
  ))

filtered_seeded <- filter_function(hmm_forward_alpha_seeded)

smoothed_seeded <-
  smooth_function(hmm_forward_alpha_seeded, hmm_backward_beta_seeded)

viterbi_seeded <- viterbi(hmm, simulated_steps$observation)

filtered_prediction_seeded <- apply(t(filtered_seeded), MARGIN = 1, which.max)
smoothed_prediction_seeded <- apply(t(smoothed_seeded), MARGIN = 1, which.max)


accuracy_function(filtered_prediction_seeded, simulated_steps_seeded$states)
accuracy_function(smoothed_prediction_seeded, simulated_steps_seeded$states)
accuracy_function(viterbi_seeded, simulated_steps_seeded$states)
```



## Task 5


```{r task_5, echo=FALSEF}

```



